package:
  name: awkward-cpp
  version: "28"
  top-level:
    - awkward_cpp

source:
  url: https://files.pythonhosted.org/packages/0e/fb/8e7db64da16a40558e3103a6d9bda0e84953a6f60041f28831b7d75cf224/awkward-cpp-28.tar.gz
  sha256: abb01c5abc00cb77225f64c205da5b05a1a9a7544c388c0d3a1c811e0d1dfe18

build:
  script: |
    export CMAKE_ARGS="${CMAKE_ARGS} -DEMSCRIPTEN=1"
  exports: whole_archive

requirements:
  run:
    - numpy

test:
  imports:
    - awkward_cpp

about:
  home: https://pypi.org/project/awkward-cpp/
  summary: CPU kernels and compiled extensions for Awkward Array
  license: BSD-3-Clause
